### ISSUE TITLE
Nyko play pad pro D pad not work on 3.0.2 version

### ISSUE THREAD

**Issue by mickchamb** [limelight-stream/limelight-android#41]
HI,

on the last version it is mentioned : Fixed Nyko Playpad controller issue.

This fix seems to have a bad effect on the pro version of playpad controller: The d-pad not working.
I try the 8.0.1 version, all works perfectly.

**Comment by WolfspiritM** [comment]
This is still an issue with version 3.0.3.
D-Pad for the nyko play pad pro is not working.

**Comment by cgutman** [comment]
Can you get a logcat log?

**Comment by mickchamb** [comment]
Yes , how I can do this?

**Comment by mickchamb** [comment]
Still not working on 3.1 version

**Comment by Austin17** [comment]
I'm glad I found this issue, and know I'm not the only one struggling with this particular setback.

Short version: I figured out a solution to the issue, and got the D-Pad responsive again in Limelight.

Long version: Based on the comments in this thread, I wanted to try the last known working version, being 3.0.1, however that doesn't seem to be supported anymore with the newer versions of the Nvidia streaming software. I then dug through the commits between 3.0.1 and 3.0.2 attempting to find something which might be related, and I stumbled across changes to the section here as follows from lines 280-284:
https://github.com/limelight-stream/limelight-android/blob/v3.1.2/app/src/main/java/com/limelight/binding/input/ControllerHandler.java

I did some research, and I found some documentation and related form posts from the Mupen64 project about the Nyko Playpad Pro controller. It seems that the original firmware on the controller defaulted to a rather odd way of transmitting the control signals from the D-Pad. An update to the Nyko controller firmware seems to have fixed that issue however.

To fix the issue in Limelight, I ended up removing those 5 lines of code, recompiling the project, and exporting my apk. I'm not sure if I'm supposed to distribute my apk? Though if someone doesn't want to build the project themselves, feel free to shoot me a message.

**Comment by mickchamb** [comment]
Hello,

I'm glad someone else have this problem to, i'm starting to think i'm the only one that have this.
I resolved this problem on my own side to.
the bug is effectively in the device context creation in line 280. I solved it by adding a test on the name to check if it is the pro version or not, like this : 
else if (devName.contains("NYKO PLAYPAD")&& !devName.contains("PRO") 
I think there is no impact on the non pro version, if someone can test with his "non pro" version.
here my compiled apk: https://mon-partage.fr/f/KfJ1Wbix/

**Comment by ENiGMA9** [comment]
Hi, unrelated to this issue, can you help me compile this thing? Write me at wishy.paradox.wish@gmail.com if you wish, please :)

**Comment by cgutman** [comment]
The Playpad Pro hack was to fix bug #37. We need to figure out why his controller worked with the fix and yours don't.

**Comment by mickchamb** [comment]
yes there is firmware update. To do this there is the app on the play store : https://play.google.com/store/apps/developer?id=Nyko+Technologies&hl=fr_FR
I used the last version : 101
The playpad pro has 4 modes : HID , icade, mouse and app.
For that i know : HID is the standard mode, icade is for ios and app could be used with the app nyko playground of the play store to remap android keyboard on touch.
I never had the #37 bug, i used the pad to play on games (like darksouls 2, batman...) that used 2 analog stick and the pad to select weapon.

**Comment by cgutman** [comment]
@mickchamb I think you're right. The user in #37 must have been using older firmware that had the d-pad duplicate event bug. I've reverted the change.
