### ISSUE TITLE
Error 521 on Lollipop

### ISSUE THREAD

**Issue by MattJeanes** [limelight-stream/limelight-android#57]
![screenshot_2015-02-10-19-49-23](https://cloud.githubusercontent.com/assets/2363642/6135150/24748e56-b15e-11e4-91de-f2303a8d6415.png)
Happens when I try to start a game or connect to open game. Closing a game works however. 

System specs:
![screenshot_2015-02-10-19-53-01](https://cloud.githubusercontent.com/assets/2363642/6135188/7fb4457c-b15e-11e4-81a8-86ee65bc48c2.png)

**Comment by cgutman** [comment]
What version of GFE and drivers are you running?

**Comment by MattJeanes** [comment]
I went to check and it had a driver update available, so I updated and now it seems to work! Thanks anyway
