### ISSUE TITLE
Need infos about compiling

### ISSUE THREAD

**Issue by ENiGMA9** [limelight-stream/limelight-android#62]
Hi, I need some infos about compiling as it failed on windows.

I want to compile myself a nonrooted KitKat version of limelight with small changes. 

What Linux do you use? Can I skip the building of c libraries therefore skipping using NDK? The process is alike building for raspberry pi? (if not, are you kind enough to explain it a bit to me?)
I built before on windows my own code but building others code is a new world filled with surprises.

Thank you and the team for this awesome piece of software :)

**Comment by cgutman** [comment]
I do most of my development in Windows with Android Studio 1.1. You should be able to just checkout this repo and import it via Android Studio. Add an ndk.dir property to the local.properties file and point it at your NDK directory.

**Comment by ENiGMA9** [comment]
Thank you so much, I actually did what i could but NOW, NOW i see what i was doing wrong.

I was importing as Gradle Project not as Android Studio, now it works FLAWLESS, thanks!

**Comment by ENiGMA9** [comment]
Finally compiled it, i was using local distribution of gradle. I switchet do gradle wrapper, everything went smooth.
