### ISSUE TITLE
Multiple controllers on Fire TV

### ISSUE THREAD

**Issue by bradsrichardson** [limelight-stream/limelight-android#65]
Limelight works fantastic except when I try to have more than 3 controllers attached to the fire TV. I am trying to run  Castle Crashers on steam from a gtx 960. I can get up to three and then nothing else is registered by the game. Tried with two 360 controllers, 2 nyko playpad pros and the amazon fire game controller. Different combos of each work up to three. Any ideas why?

**Comment by ikogan** [comment]
I had a similar problem until I remember that I also had a keyboard attached. Turns out the keyboard tool over as one of the controllers.



—

**Comment by bradsrichardson** [comment]
I think you are right, it seems to reserve a spot for the keyboard. Any workaround for this?

**Comment by cgutman** [comment]
Can you confirm that you're running v3.1.4?

**Comment by bradsrichardson** [comment]
I am running the latest version from the Amazon store which it says is 3.1.4.

**Comment by cgutman** [comment]
The fix is checked in. It will be released in the next version.
