### ISSUE TITLE
Can't connect to my PC

### ISSUE THREAD

**Issue by Rhombicuboctahedron** [limelight-stream/limelight-android#68]
When I start up Limelight on my phone it can't find my PC on my wireless network. When I manually put my IP address into the phone, it says it can't connect. I've turned off my firewall, and had opened the ports before turning it off, but it didn't work then either. I've got a GTX 970, and GFE is updated and open. If you need any info to fix this problem I'll be looking for replies. Thanks.

**Comment by Rhombicuboctahedron** [comment]
Alright, didn't know I needed to open the ports on my router's settings. Nevermind.

**Comment by rebootjac** [comment]
Rhombicuboctahedron, I'm curious what version of GFE you were running when this was closed. Thanks
